<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Fiser</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cocona" Version="2.2.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11"/>
        <PackageReference Include="OneOf" Version="3.0.271"/>
        <PackageReference Include="OneOf.SourceGenerator" Version="3.0.271"/>
        <PackageReference Include="TerminalProgressBar" Version="1.2.0"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\" />
      <Folder Include="Infra\" />
    </ItemGroup>

</Project>
