<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Fiser</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cocona" Version="2.2.0"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11"/>
        <PackageReference Include="TerminalProgressBar" Version="1.2.0"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Supervisor.Application\Supervisor.Application.csproj" />
      <ProjectReference Include="..\Supervisor.Infra\Supervisor.Infra.csproj" />
    </ItemGroup>

</Project>
